to_find = {
        "Python": 0,
        "Docker": 0,
        "Django": 0,
        "DRF": 0,
        "GIT": 0,
        "SQL": 0,
        "REST": 0,
        "AWS": 0,
        "Linux": 0,
        "PostgreSQL": 0,
        "Pyramid": 0,
        "asyncio": 0,
        "aiohttp": 0,
        "NoSQL": 0,
        "HTML": 0,
        "CSS": 0,
        "FastAPI": 0,
        "Graphql": 0,
        "JS": 0,
        "React": 0,
        "networking": 0,
        "microservice": 0,
        "MongoDB": 0,
        "algorithms": 0,
        "OOP": 0,
        "git": 0,
    }